server:
  port: 8080

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_jxc?characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
     database: mysql
   thymeleaf:
    cache: false